name: 🚀 Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Release Please
    if: ${{ github.event_name == 'push' }}
    uses: equinor/ops-actions/.github/workflows/release-please-manifest.yml@792c28d178029e9d2b5ae027e3acbe18da89e9ed # v9.38.2
    permissions:
      contents: write
      pull-requests: write
      issues: write

  deploy-dev:
    name: Deploy Dev
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/docker.yml
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      tag: dev
      environment: dev
      api_url: https://nstuning-api-dev.prod.tumogroup.com/api
      tag_latest: false

  get-tag:
    name: Get Release Tag
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Get release tag
        id: get-tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(gh api repos/${{ github.repository }}/releases/latest --jq '.tag_name')
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

  deploy-prod:
    name: Deploy Prod
    needs: [release-please, get-tag]
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/docker.yml
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      tag: ${{ needs.get-tag.outputs.tag }}
      environment: prod
      api_url: https://nstuning-api.prod.tumogroup.com/api
      tag_latest: true

  update-chart:
    name: Update Chart
    needs: [release-please, deploy-prod, get-tag]
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    permissions:
      contents: read
    uses: sondresjolyst/tumogroup-charts/.github/workflows/update-chart.yml@main
    secrets:
      CHARTS_PAT: ${{ secrets.CHARTS_PAT }}
    with:
      chart_name: nstuning-app
      tag: ${{ needs.get-tag.outputs.tag }}
